### ISSUE TITLE
Rewrapping of meshes in new version

### ISSUE THREAD

**Issue by michaelgoetze** [mrachinskiy/booltron#7]
**Please complete the following information**
Operating system: Windows 10
Blender version: 2.81
Add-on version: 2.4.2

**Describe the bug**
I wanted to recreate the functionality mentioned in this post in the current:
[https://blender.stackexchange.com/a/78109](url)
I couldn't manage to rewrap a simple join of two objects  

![image](https://user-images.githubusercontent.com/46775781/75248288-31e50f80-57d4-11ea-9522-45c2e80012be.png)
This should only serve as a simple example for more complex meshes with vertices inside a mesh. Even though this might not have been the intended use of Booltron, I think it is a very intriguing feature, that would be worth preserving.

**Comment by mrachinskiy** [comment]
That workaround was possible due to Carve boolean solver, which is not available since Bender 2.80.
So unfortunately this method is no longer works with Booltron.

You could try separating each mesh into its own object and then use Union operation.

Or you could look into Blender feature that was developed specifically to handle this case:

* Edit Mode > Face > Intersect (Knife)

It will split selected meshes along intersection, including self-intersected geometry, but you will have to manually remove extra parts and merge generated vertices.

**Comment by mrachinskiy** [comment]
If topology of your mesh is not important, then you could also try Voxel Remesh: https://twitter.com/pablodp606/status/1161688160734253056

**Comment by michaelgoetze** [comment]
Thanks! that's a great tip!

Am Di., 25. Feb. 2020 um 22:25 Uhr schrieb Mikhail Rachinskiy <
notifications@github.com>:
